### ISSUE TITLE
How the hell am i meant to get the powerup using that one preset??? (I will explain on call trust me)

### ISSUE THREAD

**Issue by ellithot** [rednir/KajamGame#25]

**Comment by rednir** [comment]
![image](https://user-images.githubusercontent.com/10225220/138534489-49ded1c8-a0f2-4a2f-828f-6075efd0a61a.png)
LUCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
