### ISSUE TITLE
Make audio assets

### ISSUE THREAD

**Issue by rednir** [rednir/KajamGame#6]
Sound effects
- [x] Button press
- [x] Game start
- [x] Life lost
- [x] Death
- [x] Item pick up
- [ ] Next environment
- [x] Player jump

Music
- [x] Main menu
- [x] something in game music something
- [x] Results screen

**Comment by ellithot** [comment]
instead of adding a sound for the next environment mayb speed up the music slightly every time it goes 'faster!'
